# Generated by Django 5.0.4 on 2024-04-03 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine_type', models.CharField(choices=[('AFRICAN', 'African'), ('INDIAN', 'Indian'), ('CHINESE', 'Chinese'), ('WEST_AFRICAN', 'West African'), ('ITALIAN', 'Italian'), ('EUROPEAN', 'European')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApi.restaurantowner')),
            ],
        ),
    ]
